#!/bin/sh -x

perl -pi -e 's/\&#x0370;/Ͱ/g' *.xml
perl -pi -e 's/\&#x0371;/ͱ/g' *.xml
perl -pi -e 's/\&#x0372;/Ͳ/g' *.xml
perl -pi -e 's/\&#x0373;/ͳ/g' *.xml
perl -pi -e 's/\&#x0374;/ʹ/g' *.xml
perl -pi -e 's/\&#x0375;/͵/g' *.xml
perl -pi -e 's/\&#x0376;/Ͷ/g' *.xml
perl -pi -e 's/\&#x0377;/ͷ/g' *.xml
perl -pi -e 's/\&#x037A;/ͺ/g' *.xml
perl -pi -e 's/\&#x037B;/ͻ/g' *.xml
perl -pi -e 's/\&#x037C;/ͼ/g' *.xml
perl -pi -e 's/\&#x037D;/ͽ/g' *.xml
perl -pi -e 's/\&#x037E;/;/g' *.xml
perl -pi -e 's/\&#x0384;/΄/g' *.xml
perl -pi -e 's/\&#x0385;/΅/g' *.xml
perl -pi -e 's/\&#x0386;/Ά/g' *.xml
perl -pi -e 's/\&#x0387;/·/g' *.xml
perl -pi -e 's/\&#x0388;/Έ/g' *.xml
perl -pi -e 's/\&#x0389;/Ή/g' *.xml
perl -pi -e 's/\&#x038A;/Ί/g' *.xml
perl -pi -e 's/\&#x038C;/Ό/g' *.xml
perl -pi -e 's/\&#x038E;/Ύ/g' *.xml
perl -pi -e 's/\&#x038F;/Ώ/g' *.xml
perl -pi -e 's/\&#x0390;/ΐ/g' *.xml
perl -pi -e 's/\&#x0391;/Α/g' *.xml
perl -pi -e 's/\&#x0392;/Β/g' *.xml
perl -pi -e 's/\&#x0393;/Γ/g' *.xml
perl -pi -e 's/\&#x0394;/Δ/g' *.xml
perl -pi -e 's/\&#x0395;/Ε/g' *.xml
perl -pi -e 's/\&#x0396;/Ζ/g' *.xml
perl -pi -e 's/\&#x0397;/Η/g' *.xml
perl -pi -e 's/\&#x0398;/Θ/g' *.xml
perl -pi -e 's/\&#x0399;/Ι/g' *.xml
perl -pi -e 's/\&#x039A;/Κ/g' *.xml
perl -pi -e 's/\&#x039B;/Λ/g' *.xml
perl -pi -e 's/\&#x039C;/Μ/g' *.xml
perl -pi -e 's/\&#x039D;/Ν/g' *.xml
perl -pi -e 's/\&#x039E;/Ξ/g' *.xml
perl -pi -e 's/\&#x039F;/Ο/g' *.xml
perl -pi -e 's/\&#x03A0;/Π/g' *.xml
perl -pi -e 's/\&#x03A1;/Ρ/g' *.xml
perl -pi -e 's/\&#x03A3;/Σ/g' *.xml
perl -pi -e 's/\&#x03A4;/Τ/g' *.xml
perl -pi -e 's/\&#x03A5;/Υ/g' *.xml
perl -pi -e 's/\&#x03A6;/Φ/g' *.xml
perl -pi -e 's/\&#x03A7;/Χ/g' *.xml
perl -pi -e 's/\&#x03A8;/Ψ/g' *.xml
perl -pi -e 's/\&#x03A9;/Ω/g' *.xml
perl -pi -e 's/\&#x03AA;/Ϊ/g' *.xml
perl -pi -e 's/\&#x03AB;/Ϋ/g' *.xml
perl -pi -e 's/\&#x03AC;/ά/g' *.xml
perl -pi -e 's/\&#x03AD;/έ/g' *.xml
perl -pi -e 's/\&#x03AE;/ή/g' *.xml
perl -pi -e 's/\&#x03AF;/ί/g' *.xml
perl -pi -e 's/\&#x03B0;/ΰ/g' *.xml
perl -pi -e 's/\&#x03B1;/α/g' *.xml
perl -pi -e 's/\&#x03B2;/β/g' *.xml
perl -pi -e 's/\&#x03B3;/γ/g' *.xml
perl -pi -e 's/\&#x03B4;/δ/g' *.xml
perl -pi -e 's/\&#x03B5;/ε/g' *.xml
perl -pi -e 's/\&#x03B6;/ζ/g' *.xml
perl -pi -e 's/\&#x03B7;/η/g' *.xml
perl -pi -e 's/\&#x03B8;/θ/g' *.xml
perl -pi -e 's/\&#x03B9;/ι/g' *.xml
perl -pi -e 's/\&#x03BA;/κ/g' *.xml
perl -pi -e 's/\&#x03BB;/λ/g' *.xml
perl -pi -e 's/\&#x03BC;/μ/g' *.xml
perl -pi -e 's/\&#x03BD;/ν/g' *.xml
perl -pi -e 's/\&#x03BE;/ξ/g' *.xml
perl -pi -e 's/\&#x03BF;/ο/g' *.xml
perl -pi -e 's/\&#x03C0;/π/g' *.xml
perl -pi -e 's/\&#x03C1;/ρ/g' *.xml
perl -pi -e 's/\&#x03C2;/ς/g' *.xml
perl -pi -e 's/\&#x03C3;/σ/g' *.xml
perl -pi -e 's/\&#x03C4;/τ/g' *.xml
perl -pi -e 's/\&#x03C5;/υ/g' *.xml
perl -pi -e 's/\&#x03C6;/φ/g' *.xml
perl -pi -e 's/\&#x03C7;/χ/g' *.xml
perl -pi -e 's/\&#x03C8;/ψ/g' *.xml
perl -pi -e 's/\&#x03C9;/ω/g' *.xml
perl -pi -e 's/\&#x03CA;/ϊ/g' *.xml
perl -pi -e 's/\&#x03CB;/ϋ/g' *.xml
perl -pi -e 's/\&#x03CC;/ό/g' *.xml
perl -pi -e 's/\&#x03CD;/ύ/g' *.xml
perl -pi -e 's/\&#x03CE;/ώ/g' *.xml
perl -pi -e 's/\&#x03CF;/Ϗ/g' *.xml
perl -pi -e 's/\&#x03D0;/ϐ/g' *.xml
perl -pi -e 's/\&#x03D1;/ϑ/g' *.xml
perl -pi -e 's/\&#x03D2;/ϒ/g' *.xml
perl -pi -e 's/\&#x03D3;/ϓ/g' *.xml
perl -pi -e 's/\&#x03D4;/ϔ/g' *.xml
perl -pi -e 's/\&#x03D5;/ϕ/g' *.xml
perl -pi -e 's/\&#x03D6;/ϖ/g' *.xml
perl -pi -e 's/\&#x03D7;/ϗ/g' *.xml
perl -pi -e 's/\&#x03D8;/Ϙ/g' *.xml
perl -pi -e 's/\&#x03D9;/ϙ/g' *.xml
perl -pi -e 's/\&#x03DA;/Ϛ/g' *.xml
perl -pi -e 's/\&#x03DB;/ϛ/g' *.xml
perl -pi -e 's/\&#x03DC;/Ϝ/g' *.xml
perl -pi -e 's/\&#x03DD;/ϝ/g' *.xml
perl -pi -e 's/\&#x03DE;/Ϟ/g' *.xml
perl -pi -e 's/\&#x03DF;/ϟ/g' *.xml
perl -pi -e 's/\&#x03E0;/Ϡ/g' *.xml
perl -pi -e 's/\&#x03E1;/ϡ/g' *.xml
perl -pi -e 's/\&#x03E2;/Ϣ/g' *.xml
perl -pi -e 's/\&#x03E3;/ϣ/g' *.xml
perl -pi -e 's/\&#x03E4;/Ϥ/g' *.xml
perl -pi -e 's/\&#x03E5;/ϥ/g' *.xml
perl -pi -e 's/\&#x03E6;/Ϧ/g' *.xml
perl -pi -e 's/\&#x03E7;/ϧ/g' *.xml
perl -pi -e 's/\&#x03E8;/Ϩ/g' *.xml
perl -pi -e 's/\&#x03E9;/ϩ/g' *.xml
perl -pi -e 's/\&#x03EA;/Ϫ/g' *.xml
perl -pi -e 's/\&#x03EB;/ϫ/g' *.xml
perl -pi -e 's/\&#x03EC;/Ϭ/g' *.xml
perl -pi -e 's/\&#x03ED;/ϭ/g' *.xml
perl -pi -e 's/\&#x03EE;/Ϯ/g' *.xml
perl -pi -e 's/\&#x03EF;/ϯ/g' *.xml
perl -pi -e 's/\&#x03F0;/ϰ/g' *.xml
perl -pi -e 's/\&#x03F1;/ϱ/g' *.xml
perl -pi -e 's/\&#x03F2;/ϲ/g' *.xml
perl -pi -e 's/\&#x03F3;/ϳ/g' *.xml
perl -pi -e 's/\&#x03F4;/ϴ/g' *.xml
perl -pi -e 's/\&#x03F5;/ϵ/g' *.xml
perl -pi -e 's/\&#x03F6;/϶/g' *.xml
perl -pi -e 's/\&#x03F7;/Ϸ/g' *.xml
perl -pi -e 's/\&#x03F8;/ϸ/g' *.xml
perl -pi -e 's/\&#x03F9;/Ϲ/g' *.xml
perl -pi -e 's/\&#x03FA;/Ϻ/g' *.xml
perl -pi -e 's/\&#x03FB;/ϻ/g' *.xml
perl -pi -e 's/\&#x03FC;/ϼ/g' *.xml
perl -pi -e 's/\&#x03FD;/Ͻ/g' *.xml
perl -pi -e 's/\&#x03FE;/Ͼ/g' *.xml
perl -pi -e 's/\&#1023;/Ͽ/g' *.xml
perl -pi -e 's/\&#03FF;/Ͽ/g' *.xml
